// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	InsertUser(ctx context.Context) (sql.Result, error)
	UpdateUser(ctx context.Context) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
