// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const insertUser = `-- name: InsertUser :execresult
INSERT INTO users (name, email) VALUES (?, ?)
`

type InsertUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertUser, arg.Name, arg.Email)
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users 
SET 
    name = COALESCE(?, name),
    email = COALESCE(?, email)
WHERE id = ?
`

type UpdateUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser, arg.Name, arg.Email, arg.ID)
}
