// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const insertUser = `-- name: InsertUser :execresult
INSERT INTO users (name, email) VALUES ($1, $2)
`

func (q *Queries) InsertUser(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertUser)
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users 
SET 
    name = COALESCE($2, name),
    email = COALESCE($3, email)
WHERE id = $1
`

func (q *Queries) UpdateUser(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser)
}
